# Generated by Django 4.2.29 on 2026-06-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_voice_character_update_time_character_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='character',
            name='voice',
        ),
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.TextField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
