# Generated by Django 4.2.29 on 2026-06-21 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_character_update_time_remove_character_voice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
